pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("com.gradle.develocity") version "4.3"
    id("com.gradle.common-custom-user-data-gradle-plugin") version "2.4.0"
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

develocity {
    server = "https://ge.solutions-team.gradle.com/"
    allowUntrustedServer = true
    edgeDiscovery = true
    buildScan {
        publishing.onlyIf { it.isAuthenticated }
        obfuscation {
            ipAddresses { addresses -> addresses.map { "0.0.0.0" } }
        }
    }
}

rootProject.name = "androidRectangle120modules"

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
include(":core:push")
include(":core:contact")
include(":core:login")
include(":core:identity")
include(":core:checkout")
include(":core:cart")
include(":core:user")
include(":core:profile")
include(":core:feed")
include(":core:comment")
include(":core:post")
include(":core:search")
include(":core:location")
include(":core:network")
include(":core:sync")
include(":core:share")
include(":core:group")
include(":core:message")
include(":core:notification")
include(":core:setting")
include(":core:account")
include(":core:session")
include(":core:analytics")
include(":core:report")
include(":feature:log")
include(":feature:status")
include(":feature:metric")
include(":feature:task")
include(":feature:calendar")
include(":feature:event")
include(":feature:alarm")
include(":feature:timer")
include(":feature:file")
include(":feature:document")
include(":feature:note")
include(":feature:todo")
include(":feature:list")
include(":feature:map")
include(":feature:weather")
include(":feature:forecast")
include(":feature:news")
include(":feature:article")
include(":feature:podcast")
include(":feature:video")
include(":feature:photo")
include(":feature:gallery")
include(":feature:media")
include(":feature:audio")
include(":domain:playlist")
include(":domain:push-contact")
include(":domain:contact-contact")
include(":domain:login-contact")
include(":domain:identity-contact")
include(":domain:checkout-contact")
include(":domain:cart-contact")
include(":domain:user-contact")
include(":domain:profile-contact")
include(":domain:feed-contact")
include(":domain:comment-contact")
include(":domain:post-contact")
include(":domain:search-contact")
include(":domain:location-contact")
include(":domain:network-contact")
include(":domain:sync-contact")
include(":domain:share-contact")
include(":domain:group-contact")
include(":domain:message-contact")
include(":domain:notification-contact")
include(":domain:setting-contact")
include(":domain:account-contact")
include(":domain:session-contact")
include(":domain:analytics-contact")
include(":repository:report-contact")
include(":repository:log-contact")
include(":repository:status-contact")
include(":repository:metric-contact")
include(":repository:task-contact")
include(":repository:calendar-contact")
include(":repository:event-contact")
include(":repository:alarm-contact")
include(":repository:timer-contact")
include(":repository:file-contact")
include(":repository:document-contact")
include(":repository:note-contact")
include(":repository:todo-contact")
include(":repository:list-contact")
include(":repository:map-contact")
include(":repository:weather-contact")
include(":repository:forecast-contact")
include(":repository:news-contact")
include(":repository:article-contact")
include(":repository:podcast-contact")
include(":repository:video-contact")
include(":repository:photo-contact")
include(":repository:gallery-contact")
include(":repository:media-contact")
include(":model:audio-contact")
include(":model:playlist-contact")
include(":model:push-login")
include(":model:contact-login")
include(":model:login-login")
include(":model:identity-login")
include(":model:checkout-login")
include(":model:cart-login")
include(":model:user-login")
include(":model:profile-login")
include(":model:feed-login")
include(":model:comment-login")
include(":model:post-login")
include(":model:search-login")
include(":model:location-login")
include(":model:network-login")
include(":model:sync-login")
include(":model:share-login")
include(":model:group-login")
include(":model:message-login")
include(":model:notification-login")
include(":model:setting-login")
include(":model:account-login")
include(":model:session-login")
include(":app:app")
