plugins {
    id("awesome.androidapp.plugin")
    id("io.github.cdsap.r8booster") version "0.0.4"
}

dependencies {
    implementation(project(":model:audio-contact"))
    implementation(project(":model:playlist-contact"))
    implementation(project(":model:push-login"))
    implementation(project(":model:contact-login"))
    implementation(project(":model:login-login"))
    implementation(project(":model:identity-login"))
    implementation(project(":model:checkout-login"))
    implementation(project(":model:cart-login"))
    implementation(project(":model:user-login"))
    implementation(project(":model:profile-login"))
    implementation(project(":model:feed-login"))
    implementation(project(":model:comment-login"))
    implementation(project(":model:post-login"))
    implementation(project(":model:search-login"))
    implementation(project(":model:location-login"))
    implementation(project(":model:network-login"))
    implementation(project(":model:sync-login"))
    implementation(project(":model:share-login"))
    implementation(project(":model:group-login"))
    implementation(project(":model:message-login"))
    implementation(project(":model:notification-login"))
    implementation(project(":model:setting-login"))
    implementation(project(":model:account-login"))
    implementation(project(":model:session-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)

    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)

    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)


}
